#!/bin/sh
# Script to change hyprland gaps.

case "$1" in
	'add') 
		hyprctl getoption general:gaps_out | awk -v size=$2 '/int/ { print $2+size }' | xargs -ro hyprctl keyword general:gaps_out
					;;
	'min') 
		hyprctl getoption general:gaps_out | awk -v size=$2 '/int/ { if($2>0) print $2-size }' | xargs -ro hyprctl keyword general:gaps_out
					;;
	'reset') 
		hyprctl --batch "keyword general:gaps_out $2; keyword decoration:rounding 10"
					;;
	'maximize') 
		hyprctl --batch "keyword general:gaps_out 0; keyword decoration:rounding 0"
					;;
esac	

