#!/bin/sh
# Script to choose and set wallpaper.

IMAGE_CHOOSED=$(sxiv -t -o -r /extra/WALLPAPERS/wallpapers/)

if [[ ! -z "$IMAGE_CHOOSED" ]]; then
  pkill -9 swaybg
  swaybg --mode fill --image "$IMAGE_CHOOSED"
else
  exit 0
fi
