#!/bin/sh
# Switch between monitors. Meant to be used with BSPWM.

CHOICE=$(echo -e "External Only\nLaptop Only" | \
	rofi -dmenu -i -no-show-icons -p monitor -config $HOME/.config/rofi/launcher.rasi)

case "$CHOICE" in
	'External Only') 
		xrandr --output HDMI-1 --primary --mode 1366x768 --rotate normal --brightness 0.65 --left-of eDP-1 \
			--output eDP-1 --off 
					;;
	'Laptop Only') 
		xrandr --output eDP-1 --primary --mode 1366x768 --rotate normal --brightness 0.65 --right-of HDMI-1 \
			--output HDMI-1 --off 
					;;
esac	

bspc monitor --reset-desktops 1 2 3 4
